### PR TITLE
Various updates

### PR DESCRIPTION
**Pull request by tokejepsen**
closing #16 
- all plugins are now process on instances only
- labelled all plugins

### CODE REVIEW

**Comment by tokejepsen** [comment]
@mkolar could you give this a go at your studio? Just want to check I've remained studio neutral.

**Comment by tokejepsen** [comment]
injecting context is fixed

**Comment by tokejepsen** [comment]
@mkolar did you try this at your studio?

**Comment by mkolar** [comment]
Not yet. Didn't have time

**Comment by mkolar** [comment]
This seems to be working fine for us

**Pull request merged**
