### PR TITLE
Remote submission and Dependencies

### PR DESCRIPTION
**Pull request by tokejepsen**
- added remote submission feature
- renamed plugin
- added dependencies feature

### CODE REVIEW

**Comment by mottosso** [comment]
Could you give a brief overview of how the remote submission and dependency features works?

**Comment by tokejepsen** [comment]
Remote submission is to submit jobs without the need for a VPN connection to the Deadline server.

Dependencies work by stopping jobs from processing, until the dependencies are completed.

You can see the usage instructions in the readme; https://github.com/tokejepsen/pyblish-deadline/blob/master/README.md

**Comment by mottosso** [comment]
Ah, you already had, that's perfect. Looks good to me.

**Comment by tokejepsen** [comment]
- fixed submission not respecting the toggle state in the ui

Going to leave this for a little while, to make sure there are no problems here.

**Comment by mottosso** [comment]
Ok

**Comment by tokejepsen** [comment]
Everything seems to be working well here, merging.

**Pull request merged**
