### PR TITLE
remote submission working version

### PR DESCRIPTION
**Pull request by tokejepsen**

### CODE REVIEW

**Comment by mottosso** [comment]
Looking good!

I'm a bit skeptical about the submodule however.

1. It's different from other Pyblish repositories
2. It will be more difficult to distribute via e.g. pip, because pyblish_deadline isn't the only top-level Python package
3. It will require end-users to install via either `--recursive` on `git pull` or do a `git clone` followed by a `git submodule update` (submodules aren't included in the initial clone by default).

There is one final thing which isn't submodule specific and can be worked around.

- It modifies the global `sys.path`. This is bad simply because it's global and affects things outside of Pyblish Deadline.

To fix this, you could make sure to restore `sys.path` after you've imported `requests`.

```python
sys.path.pop()
``` 

But it wouldn't stop others from then using the same request due to Python's caching mechanism. I.e. any module imported a second time will simply use the one already imported.

An ideal solution is to instead bundle the package with your Python package.

```python
from pyblish_deadline.vendor import requests
```

**Comment by tokejepsen** [comment]
Have updated this to bundle requests.

**Comment by mottosso** [comment]
Cool, does this work for you? Any problems?

**Comment by tokejepsen** [comment]
Tested it successfully here.

**Comment by mottosso** [comment]
Mm, I mean for you personally, how does this solution feel? It lacks some of the dynamic benefits of subpackages, but it should hopefully make for easier maintenance long term.

**Comment by tokejepsen** [comment]
> how does this solution feel?

I think its a better solution, as the vendor is locked down. Updating to newer version is pretty simple.

**Comment by mottosso** [comment]
Awesome, looks good to me.

**Pull request closed without merging**
