### PR TITLE
Support for Job Dependencies and Auxiliary Files

### PR DESCRIPTION
**Pull request by tokejepsen**
See readme for details.

### CODE REVIEW

**Comment by mottosso** [comment]
This looks killer. :)

**Comment by mottosso** [comment]
What do you think about including an example extractor or integrator? Or collector? Whatever it is that you use with this. I'm curious as to how it could look in practice.

**Comment by tokejepsen** [comment]
> What do you think about including an example extractor or integrator? Or collector?

Good idea, I'll make an issue for me to do an example.

**Comment by mottosso** [comment]
Sweet

**Comment by tokejepsen** [comment]
Merging this now, as it's been working for a while now.

**Pull request merged**
