### PR TITLE
Using ftrack extension fully

### PR DESCRIPTION
**Pull request by tokejepsen**

### CODE REVIEW

**Comment by mottosso** [comment]
Would you like write access to this repo?

**Comment by tokejepsen** [comment]
Yes, please:)

**Comment by mottosso** [comment]
Done

**Comment by mottosso** [comment]
As I told @mkolar, just an FYI, don't push directly into the pyblish/pyblish-deadline repo, always do pull-requests. And as a courtesy, try not to merge your own requests immediately, but rather let them breathe for a few minutes at least, giving others a chance to chime in.

Other than that, keep it safe. :)

**Comment by tokejepsen** [comment]
Cool, yeah. Milan tested this at Kredenc so its been tested everywhere its in use:)

**Comment by mottosso** [comment]
Excellent, and on that note, it would be very good to try and keep any communication about development on an open channel. I know it's sometimes easier to pop up a chat window and talk directly, but it makes issues and pull-requests tricky to follow for anyone who isn't in the conversation.

And if you have to, try repeating the vital parts of the conversation where it makes sense so others can catch up.

Sound ok?

**Comment by tokejepsen** [comment]
yup, will do from now on.

**Comment by mottosso** [comment]
Perfect, thanks a million @tokejepsen!

**Pull request merged**
