### PR TITLE
Fixes to work with pyblish-ftrack

### PR DESCRIPTION
**Pull request by tokejepsen**
Had to add ftrack data to the instances, to activate the processing.

Here I'm modifying the data with ```ftrackAssetName``` in a validator, so it works with the pipeline.
Not entirely sure this is a good way to go, but its working.

### CODE REVIEW

**Comment by mottosso** [comment]
> modifying the data with ftrackAssetName in a **validator**

:warning:

Be careful.

**Comment by tokejepsen** [comment]
> Be careful.

I know, that's why I'm not happy with it.

**Comment by mottosso** [comment]
How about this one? :)

**Comment by tokejepsen** [comment]
Same goes for this one:)

**Pull request closed without merging**
